config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :products
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :store_name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_save { self.email = email.downcase } 

    has_many :customer
    has_many :product
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
    def authorize
      unless logged_in?
        redirect_to root_url
      end
   end

def correct_user?
  @user = User.find(params[:id])
  unless current_user == @user
    redirect_to users_path
  end
end


   
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authorize
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @name_search = params[:name]
    @customers = Customer.where(user_id: current_user.id).where("name ilike ?", "%#{@name_search}%")
  end

  def show
    @customer = Customer.find(params[:id])
    unless current_user.id == @customer.user_id
      redirect_to customers_path
    end
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
 
    unless current_user.id == @customer.user_id
      redirect_to customers_path
    end
  end

  def create
    @customer = Customer.new(customer_params)

    @customer.user_id = current_user.id

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Cliente cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Cliente atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    unless current_user.id == @customer.user_id
      redirect_to products_path
    end

    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Cliente deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :contact, :user_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @name_search = params[:name]
    @products = Product.where(user_id: current_user.id).where("name ilike ?", "%#{@name_search}%")
  end

  def show
    @product = Product.find(params[:id])
    unless current_user.id == @product.user_id
      redirect_to products_path
    end
  end

  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])

    @product.price = @product.price == nil ? 0 : @product.price 
    unless current_user.id == @product.user_id
      redirect_to products_path
    end
  end

  def create
    @product = Product.new(product_params)

    @product.user_id = current_user.id
    @product.amount = 0

    @product.price = @product.price == nil ? 0 : @product.price

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    unless current_user.id == @product.user_id
      redirect_to products_path
    end
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Produto deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :amount, :user_id, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create  
     @user = User.find_by(email: params[:session][:email].downcase)
     if @user && @user.authenticate(params[:session][:password])
                sign_in(@user)
                redirect_to current_user
     else
      render action: :new
     end
   end
   def destroy
     sign_out
     redirect_to root_url
    end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorize, except: [:new, :create]
	before_action :correct_user?, only: [:edit, :update, :destroy, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: "Usuário foi criado com sucesso!"
      #Usuário depois de cadastrado acessa o sistema automaticamente
      sign_in(@user)
    else 
      render action: :new
    end
  end

  def index
    @users = User.where(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id]) 
  end
   
  def update
    @user = User.find(params[:id]) 
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render action: :edit
    end
  end
   
  def destroy
    @user = User.find(params[:id]) 
    @user.destroy
    sign_out
    redirect_to root_path
  end


  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :store_name)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
	def post_date(date)
	    date.strftime("%d/%m/%Y - %H:%M")
  	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user_id) 
                session[:user_id] = @user.id 
    end 
    def current_user
                @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
                if current_user.present?
                           redirect_to users_path
                end
    end
    def logged_in?
        !current_user.nil?
    end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end

end 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation", class="alert alert-danger">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <label>Nome</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
  <label>Contato principal</label>
    <%= f.text_field :contact, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-default btn-xs" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h3>Editiando Cliente</h3>

<%= render 'form' %>

<%= link_to 'Ver', @customer %> |
<%= link_to 'Listar Clientes', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-9">
        <% button_to "Novo Cliente", new_customer_path, :method => "get", class: "btn btn-default btn-xs" %>
        <% link_to 'Novo Cliente', new_customer_path %>
        <%= link_to " Novo cliente", new_customer_path, :method => "get", class: " fa fa-plus-circle btn btn-default btn-xs"%> 
      </div>

      <div align="right" class="col-md-3">
        <%= form_tag customers_path, method: :get do  %>
            <div class="input-group input-group-sm">
              <span class="input-group-addon" id="sizing-addon3"><i class="fa fa-search label-tema" aria-hidden="true"></i></span>
              <%= text_field_tag :name, @nome_buscar, class: "form-control", placeholder: "buscar clientes ... " %>
              <% button_to "Buscar", nil, class: "fa fa-search btn btn-defaut btn-xs" %>
            </div>            
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <% @customers.each do |customer| %>
  <div class="col-md-3">
    <ul class="small list-group ">
      <strong><% link_to customer.name, customer, class: 'list-group-item', title: 'ver cliente', align: 'center' %></strong>
      <li class="list-group-item list-group-item-info" align="center">
        <strong><%= customer.name %></strong>
      </li>
      <li class="list-group-item">
        <i class="fa fa-book label-tema label-tema" aria-hidden="true"></i> Em construção<br>
      </li>
      <li class="list-group-item">
        <% link_to ' visualizar', customer, class: 'btn btn-default btn-xs fa fa-eye', title: 'ver cliente' %>
        <button type="button" class="btn btn-default btn-xs fa fa-eye" data-toggle="modal" title="Visualizar cliente" data-target= <%= "#" + customer.id.to_s %> > visualizar</button>
        <%= link_to ' editar', edit_customer_path(customer), class: 'btn btn-default btn-xs fa fa-pencil-square-o', title: 'editar cliente' %>
      </li>
    </ul>
  </div>
  <!-- Modal ver cliente -->
  <div id=<%= customer.id.to_s %> class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 align="center" class="label-tema modal-title"><i class="fa fa-eye" aria-hidden="true"></i><%= " "+ customer.name %></h4>
        </div>
        <div class="modal-body">
          <div class="panel panel-default">
            <div class="panel-body">
              <p><strong>Nome: </strong><%= customer.name %></p>
              <p><strong>Contato: </strong><%= customer.contact %></p>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Sair</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>  
</div>

app/views/customers/new.html.erb
<h3>Novo Cliente</h3>

<%= render 'form' %>

<%= link_to 'Listar clientes', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @customer.contact %>
</p>

<p>
  <strong>User:</strong>
  <%= @customer.user_id %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/_header.html.erb
<%= nav_bar brand: "Pop-Market", brand_link: root_url do %>
    <%= menu_group pull: :left  do %>
        <% if logged_in? %>
        <%= menu_item " Produtos", products_path, class: 'fa fa-suitcase' %>
        <%= menu_item " Clientes", customers_path, class: 'fa fa-id-card' %>
        <% end %>
     <% end %>
    <%= menu_group pull: :right  do %>
        <% if logged_in? %>
          <%= menu_item " "+current_user.store_name, edit_user_path(current_user), class: 'fa fa-shopping-bag' %>
          <%= menu_item " Sair", sign_out_path, method: "delete", class: 'fa fa-sign-out' %>
        <% else %>
          <% menu_item "Entrar", root_path, class: 'fa fa-sign-in' %>
          <li class="active">
            <a href="" data-toggle="modal" data-target="#loginModal" class="fa fa-sign-in"> Entrar</a>
          </li>
        <% end %>
     <% end %>
<% end %>




<!-- Modal Login -->
<div id="loginModal" class="modal fade" role="dialog">
<div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Login</h4>
    </div>
    <div class="modal-body">
      <%= form_for :session, url: sign_in_path do |f| %>
        <div class="form-group">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, class: "input-sm form-control" %>
        </div>
       
        <div class="form-group">
          <%= f.label :senha %><br />
          <%= f.password_field :password, autocomplete: "off", class: "input-sm form-control" %>
        </div>           
    </div>
    <div class="modal-footer">
      <%= f.submit "Entrar", class: "btn btn-default btn-xs" %>
      <% end %> 
      <button type="button" class="btn btn-default btn-xs" data-dismiss="modal">Sair</button>
    </div>
  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopMarket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation", class="alert alert-danger">
        <ul>
          <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %> 
  <div class="form-group">
    <label>Nome</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Descrição</label>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Preço</label>
    <%= f.number_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-default btn-xs" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editando produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Ver', @product %> |
<%= link_to 'Voltar', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-9">
        <% button_to "Novo produto", new_product_path, :method => "get", class: "btn btn-default btn-xs" %>
        <% link_to 'Novo produto', new_product_path %>
        <%= link_to " Novo produto", new_product_path, :method => "get", class: " fa fa-plus-circle btn btn-default btn-xs"%> 
      </div>
      <div align="right" class="col-md-3">
        <%= form_tag products_path, method: :get do  %>
          <div class="input-group input-group-sm">
              <span class="input-group-addon" id="sizing-addon3"><i class="fa fa-search label-tema" aria-hidden="true"></i></span>
              <%= text_field_tag :name, @name_search, class: "form-control", placeholder: "buscar produtos ... " %>
              <% button_to "Buscar", nil, class: "fa fa-search btn btn-defaut btn-xs" %>
          </div>   
        <% end %>
      </div>
    </div>  
  </div>
</div>


<table class="table table-condensed table-hover">
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><i class="fa fa-suitcase label-tema" aria-hidden="true"></i> <%= product.name %></td>
        <td align="right"><i class="label-tema" aria-hidden="true"></i> R$  <%= product.price %></td>
        <td align="right"><i class="label-tema" aria-hidden="true"></i> <%= product.amount %> disponíveis</td>
        <td align="right">
          <%= link_to 'Editar', edit_product_path(product), class: " fa fa-pencil-square-o btn btn-default btn-xs" %>
          <%= link_to 'Ver', product, class: " fa fa-eye btn btn-default btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>
<h3><%= @product.name %></h3>

<div class="panel panel-default">
  <div class="panel-body">
    <p><strong>Descrição: </strong><%= @product.description %></p>
    <p><strong>Preço: </strong><%= @product.price %></p>
    <p><strong>Quantidade: </strong><%= @product.amount %></p>
  </div>
</div>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Listar produtos', products_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation", class="alert alert-danger">

        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
<% end %>
<div class="form-group">
  <%= f.label :nome %>
  <%= f.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :store_name %>
  <%= f.text_field :store_name, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :senha %>
  <%= f.password_field :password, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label 'Confirmar Senha' %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit "Salvar", class: "btn btn-default btn-xs" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h3>Configurações do Usuário</h3>
    <%= render 'form' %>

app/views/users/index.html.erb
<h3> Usuários </h3>
<table class="table table-bordered">
  <thead>
       <tr>
         <th>Nome</th>
         <th>Loja</th>
         <th>Email</th>
         <th></th>
       </tr>
  </thead>
  <tbody>
       <% @users.each do |user| %>
         <tr>
           <td><%= user.name %></td>
           <td><%= user.store_name %></td>
           <td><%= user.email %></td>
           <td><%= link_to "Ver", user %></td>
         </tr>
      <%end%>
  </tbody>
 </table>

app/views/users/new.html.erb
<h3>Novo Usuário</h3>
<%= render 'form' %>

app/views/users/show.html.erb
<html>
<body>
	<h3> Perfil de <%= @user.name %> </h3>
	<%= @user.email %>
	<%= @user.store_name %>
	<% if current_user == @user %>
	<%= link_to "Editar", edit_user_path(current_user) %>
	<%end%>
</body>
  </html>